### ISSUE TITLE
Chucker doesn't work with macro benchmark, baseline profile

### ISSUE THREAD

**Issue by FunkyMuse** [ChuckerTeam/chucker#821]
## :writing_hand: Describe the bug

When trying to generate a macro benchmark, chucker does not work
```
Unresolved reference: chuckerteam
```

## :bomb: Steps to reproduce

1. Go to https://developer.android.com/topic/performance/baselineprofiles
2. And try to follow the steps here https://developer.android.com/topic/performance/benchmarking/macrobenchmark-overview

Inside the app module 
```gradle
 buildTypes {
        create("benchmark") {
            initWith(getByName("release"))
            signingConfig = signingConfigs.getByName("debug")
            matchingFallbacks += listOf("release")
            isDebuggable = false
        }
}
```

```gradle
debugImplementation(libs.chuck.debug)
releaseImplementation(libs.chuck.release)
```

where 
```toml
chuck-debug = { module = "com.github.chuckerteam.chucker:library", version.ref = "chuck" }
chuck-release = { module = "com.github.chuckerteam.chucker:library-no-op", version.ref = "chuck" }
```
and
```toml
chuck = "3.5.2"
```

## :wrench: Expected behavior

Being able to run the profile installer without commenting the chucker code

## :camera: Screenshots

![image](https://user-images.githubusercontent.com/25645122/168494459-4289ecc3-1c46-49eb-95fe-dfb247180e22.png)
![image](https://user-images.githubusercontent.com/25645122/168494558-b79fb37f-d89c-430e-9794-5886d094bb86.png)

## :iphone: Tech info
 - Device:  Pixel 2 API 29 emulator AOSP image
 - OS:  Android 10
 - Chucker version:  3.5.2

## :page_facing_up: Additional context

If I comment out the code
![image](https://user-images.githubusercontent.com/25645122/168494488-2460a943-072e-408a-9345-15d322985375.png)

then the baseline profile can be generated
![image](https://user-images.githubusercontent.com/25645122/168494533-57ba3680-a385-4c78-9d30-97f67fa75aab.png)
